# Generated by Django 5.2.5 on 2026-03-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead/Inquiry'), ('RENEWAL', 'Renewal'), ('FOLLOW_UP', 'Follow Up'), ('CHANGES', 'Changes'), ('COMPLETED', 'Completed'), ('DISCARDED', 'Discarded Leads')], default='LEAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('NEW', 'New Policy'), ('RENEWAL', 'Renewal'), ('CHANGES', 'Changes'), ('CANCELLATION', 'Cancellation')], max_length=20),
        ),
    ]
