# Generated by Django 5.2.5 on 2026-03-23 06:11

from django.db import migrations, models

def migrate_details_to_json(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        parsed_data = {}
        if ticket.old_details:
            lines = ticket.old_details.split('\n')
            for line in lines:
                if not line.strip() or line.strip().startswith('---'): continue
                if line.strip().startswith('[') and line.strip().endswith(']'):
                    continue
                if ':' in line:
                    parts = line.split(':', 1)
                    key = parts[0].strip()
                    val = parts[1].strip()
                    parsed_data[key] = val
        ticket.details = parsed_data
        ticket.save(update_fields=['details'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_status_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='details',
            new_name='old_details',
        ),
        migrations.AddField(
            model_name='ticket',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(migrate_details_to_json, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ticket',
            name='old_details',
        ),
        migrations.RunSQL(
            sql="""
            CREATE SEQUENCE IF NOT EXISTS ticket_no_seq START 1;
            DO $$ 
            DECLARE 
                max_val INTEGER;
            BEGIN
                SELECT COALESCE(MAX(CAST(NULLIF(regexp_replace(ticket_no, '^INS-', ''), '') AS INTEGER)), 0) 
                INTO max_val 
                FROM tickets_ticket 
                WHERE ticket_no LIKE 'INS-%';
                
                IF max_val > 0 THEN
                    PERFORM setval('ticket_no_seq', max_val);
                END IF;
            END $$;
            """,
            reverse_sql="DROP SEQUENCE IF EXISTS ticket_no_seq;"
        )
    ]
