# Generated by Django 5.2.5 on 2026-04-06 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_renewal_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_type', models.CharField(max_length=50)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('binder_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
