# Generated by Django 5.2.5 on 2026-04-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_binder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='binder_number',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='premium_amount',
        ),
        migrations.RemoveField(
            model_name='binder',
            name='status',
        ),
        migrations.AddField(
            model_name='binder',
            name='binder_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='binder',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='binder',
            name='quote_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='binder',
            name='task',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
