# Generated by Django 5.2.5 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_binder_binder_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binder",
            name="task",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
