# Generated by Django 5.2.5 on 2026-04-09

from django.db import migrations, models


def normalize_binder_task_values(apps, schema_editor):
    Binder = apps.get_model("tickets", "Binder")
    for binder in Binder.objects.all().only("id", "task"):
        raw = (binder.task or "").strip().lower()
        # Legacy free-text task values are mapped to valid enum values.
        binder.task = "COMPLETED" if "complete" in raw else "PENDING"
        binder.save(update_fields=["task"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_binder_binder_created_by"),
    ]

    operations = [
        migrations.RunPython(normalize_binder_task_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="binder",
            name="task",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
