# Generated by Django 5.2.5 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_alter_binder_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binder",
            name="binder_person",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KALPAN", "KALPAN"),
                    ("JEEL", "JEEL"),
                    ("VATSAL", "VATSAL"),
                    ("HARSH", "HARSH"),
                    ("PRINCE", "PRINCE"),
                    ("FERIL", "FERIL"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="binder",
            name="quote_person",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KALPAN", "KALPAN"),
                    ("JEEL", "JEEL"),
                    ("VATSAL", "VATSAL"),
                    ("HARSH", "HARSH"),
                    ("PRINCE", "PRINCE"),
                    ("FERIL", "FERIL"),
                ],
                max_length=150,
            ),
        ),
    ]
