# Generated by Django 5.2.17 on 2026-08-27 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_discardreopenreminderdismissal_anniversary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binder",
            name="binder_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="binder",
            name="binder_person",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="binder",
            name="quote_person",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
