# Generated by Django 5.2.5 on 2026-05-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRenewalReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField()),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_reminder_logs', to='policies.policy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('policy', 'days_before', 'channel'), name='uniq_policy_reminder_channel')],
            },
        ),
    ]
