# Generated by Django 5.2.5 on 2026-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_assigned_ticket_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('MANAGER', 'Manager')], default='AGENT', max_length=20),
        ),
    ]
