# Generated by Cursor on 2026-03-25
from django.db import migrations, models


PERMISSIONS_OPTIONS = [
    "View Tickets",
    "Create Tickets",
    "Edit Clients",
    "Delete Records",
    "Manage Billing",
    "Export Data",
]

# Defaults to match the current frontend placeholder UX.
DEFAULT_AGENT_PERMISSIONS = ["View Tickets", "Create Tickets"]
DEFAULT_ADMIN_PERMISSIONS = PERMISSIONS_OPTIONS[:]  # full set


def set_default_permissions_for_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Ensure older users get sensible defaults for the new JSON field.
    for user in User.objects.all():
        perms = getattr(user, "permissions", None)
        if not perms:
            user.permissions = (
                DEFAULT_ADMIN_PERMISSIONS if user.role == "ADMIN" else DEFAULT_AGENT_PERMISSIONS
            )
            user.save(update_fields=["permissions"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of permission labels (e.g. View Tickets, Create Tickets, ...).",
            ),
        ),
        migrations.RunPython(set_default_permissions_for_existing_users, migrations.RunPython.noop),
    ]

